global:
  enabled: true
  domain: consul
  datacenter: dc1

server:
  enabled: true
  replicas: 1
  bootstrapExpect: 1

client:
  enabled: true
  grpc: true

# consul ã® dashboard
ui:
  enabled: true

connectInject:
  enabled: true
